dist: bionic
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  repo: emathgroup/emathgroup.github.io
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - npm install -g gatsby-cli gh-pages yarn
  - yarn

script:
  - "npm run test"
after_success:
  - "echo %%%%%%%%%%%%%%%%..done..%%%%%%%%%%%%%%%%%%%%%%%%%%%%"