dist: bionic
language: node_js
git:
  depth: 1
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - .cache
deploy:
  provider: pages
  skip-cleanup: true
  repo: emathgroup/emathgroup.github.io
  target_branch: master
  github-token: $GITHUB_TOKEN
  local_dir: public
  email: "emath.ac.cn@gmail.com"
  name: "emath.Robot"
  keep-history: true
  on:
    branch: master
before_install:
  - npm install -g gatsby-cli yarn
  - yarn

script:
  - "npm run test"
after_success:
  - "npm run deploy"